name: Handle Test Dispatch

on:
  repository_dispatch:
    types: [test-dispatch]
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Print payload info
        run: |
          echo "Received dispatch from: ${{ github.event.client_payload.repo }}"
          echo "Version: ${{ github.event.client_payload.version }}"
